GET http://localhost:3000/ping

### Post login 
POST http://localhost:3000/auth/login

### Requisicao registrar usuario
POST http://localhost:3000/auth/registrar
Content-Type: application/json

{
  "nome": "João da Silva Pereira",
  "email": "joaodasilvpereira@zmail.com",
  "senha": "123456",
  "telefone": "11999999988",
  "barbeiro": false
}
